### ISSUE TITLE
About the decoder code

### ISSUE THREAD

**Issue by ZDYsszz** [PerceptionComputingLab/SCC#1]
In the train_LA_semi_contrastive.py, the seg model doesn't have has_triup keys, and its default value is False, SO the output of seg model, output1 and output2 are both decode by the same decoder,right?In other words,decoder_1 and decoder_2 is the same decoder
![image](https://user-images.githubusercontent.com/73088524/176118920-67517699-80b3-429d-b162-7eaeb83de017.png)

**Comment by ZDYsszz** [comment]
the decoder is the same decoder,but in the paper's figure,the decoders is not the same

**Comment by Suiiyu** [comment]
> In the train_LA_semi_contrastive.py, the seg model doesn't have has_triup keys, and its default value is False, SO the output of seg model, output1 and output2 are both decode by the same decoder,right?In other words,decoder_1 and decoder_2 is the same decoder ![image](https://user-images.githubusercontent.com/73088524/176118920-67517699-80b3-429d-b162-7eaeb83de017.png)

Thanks for your attention to our work. decoder_1 and decoder_2 have the same structure, but they are not the same. In the training stage, they are optimized simultaneously and do not influence each other. At the end of the training, they will obtain different weights.

**Comment by ZDYsszz** [comment]
![image](https://user-images.githubusercontent.com/73088524/176583091-d903b8cb-78fd-46ef-8e0a-a3e6a1c17e31.png)
sorry,but i still have a problem, if the two decoder are not the same,the out1 and out2 should be different, because without inital,the weights of decoders are random initialed.but the result is that out1 equals to out2, in other words,they have same weights...

**Comment by Suiiyu** [comment]
In fact, predictions of decoder-1 and decoder-2 are also equal in our experiments. But it do improve the performance compared with VNet.


By the way, our paper is followed current popular dual decoders structure and our experiments demonstrated that current setting is better than others in this task.


发自我的iPhone

------------------ Original ------------------
From: Dingyue Zheng ***@***.***&gt;
Date: 周四,6月 30,2022 11:04 上午
To: PerceptionComputingLab/SCC ***@***.***&gt;
Cc: Sue ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [PerceptionComputingLab/SCC] About the decoder code (Issue #1)





 

 sorry,but i still have a problem, if the two decoder are not the same,the out1 and out2 should be different, because without inital,the weights of decoders are random initialed.but the result is that out1 equals to out2, in other words,they have same weights...

**Comment by ZDYsszz** [comment]
well,thank you for your reply
